
name: Build and Deploy
on: 
  push:
  # 定时器
  schedule: 
    - cron:'0 */1 * * * ?'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1

    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Get suggestion
      run: npm install && npm run suggestion

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: .

    - name: Send mail ✉️
      uses: dawidd6/action-send-mail@v2
      with:
        # smtp 服务器地址
        server_address: smtp.office365.com
        # smtp 服务器端口
        server_port: 587
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: 今日穿衣建议
        body: file://index.html
        to: 2284903076@qq.com
        from: un-name 
        content_type: text/html
        convert_markdown: true

        

